# Generated by Django 3.2.15 on 2022-08-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysecapp4', '0002_auto_20220810_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user4',
            name='auth_token',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
