# Generated by Django 3.2.15 on 2022-08-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysecapp4', '0003_user4_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user4',
            name='state',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
