# Generated by Django 3.2.15 on 2022-08-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysecapp4', '0005_alter_user4_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user4',
            name='try_count',
            field=models.IntegerField(blank=True, default=False),
        ),
    ]
