# Generated by Django 3.2.15 on 2022-08-11 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=200, null=True, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('longitude', models.IntegerField(blank=True, default=None, max_length=200, null=True)),
                ('deviceId', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cysecapp3.user3')),
            ],
        ),
    ]
