# Generated by Django 3.2.15 on 2022-08-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysecapp7', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user7',
            name='credits',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
