# Generated by Django 3.2.15 on 2022-08-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cysecapp7', '0002_user7_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user7',
            old_name='credits',
            new_name='credit',
        ),
    ]
