# Generated by Django 3.2.15 on 2022-08-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysecapp7', '0003_rename_credits_user7_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user7',
            name='auth_token',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
