# Generated by Django 3.2.15 on 2022-08-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysecapp', '0002_auto_20220809_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
