# Generated by Django 3.2.15 on 2022-08-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysecapp2', '0002_alter_user2_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='user_role',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
